#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""PCAPCracker Pro - WPA/WPA2 Cracking Tool with AI Support"""
import os, re, sqlite3, subprocess, hashlib, json, time, configparser
from datetime import datetime
from pathlib import Path
from colorama import Fore, Style, init
from tqdm import tqdm
from html import escape
from groq import Groq

init(autoreset=True)

# Config
class Cfg:
    PCAP="pcap"; HASH="hash"; WL="wordlist"; RULES="rules"
    LOG="logs"; DB="pcapcracker.db"; MAX_ATT=2
    def __init__(self):
        self.POT=f"{self.HASH}/pot.pot"
        self.HTML=f"{self.LOG}/html"; self.JSON=f"{self.LOG}/json"
        for d in [self.PCAP, self.HASH, self.WL, self.RULES, self.LOG, self.HTML, self.JSON]:
            try:
                os.makedirs(d, exist_ok=True)
                if not os.access(d, os.W_OK):
                    raise PermissionError(f"Sem permissão para escrever em: {d}")
            except Exception as e:
                print(f"{Fore.RED}[✗] Erro ao criar diretório {d}: {e}{Style.RESET_ALL}")
                exit(1)

cfg=Cfg()

# HTML Template
HTML_TPL="""<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>{title}</title>
<style>*{{margin:0;padding:0;box-sizing:border-box}}
body{{font-family:'Segoe UI',Arial,sans-serif;background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);
min-height:100vh;padding:20px}}
.container{{max-width:1200px;margin:0 auto;background:rgba(255,255,255,0.98);
border-radius:20px;box-shadow:0 25px 80px rgba(0,0,0,0.4);overflow:hidden}}
.header{{background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);
color:#fff;padding:40px;text-align:center;position:relative}}
.header::after{{content:'';position:absolute;bottom:0;left:0;right:0;
height:4px;background:linear-gradient(90deg,#00f260,#0575e6,#00f260)}}
.header h1{{font-size:2.5em;margin-bottom:10px;text-shadow:2px 2px 4px rgba(0,0,0,0.3)}}
.header .subtitle{{font-size:1.1em;opacity:0.9;color:#00f260}}
.stats{{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));
gap:20px;padding:30px;background:#f8f9fa}}
.stat-card{{background:#fff;padding:25px;border-radius:15px;
box-shadow:0 5px 15px rgba(0,0,0,0.1);border-left:5px solid;
transition:transform 0.3s}}
.stat-card:hover{{transform:translateY(-5px)}}
.stat-card.success{{border-color:#00f260}}
.stat-card.info{{border-color:#0575e6}}
.stat-card.warning{{border-color:#ffd32a}}
.stat-label{{font-size:0.9em;color:#6c757d;text-transform:uppercase;
letter-spacing:1px;margin-bottom:10px}}
.stat-value{{font-size:2.5em;font-weight:bold;color:#1a1a2e}}
.content{{padding:40px}}
.section{{margin-bottom:40px}}
.section-title{{font-size:1.8em;color:#1a1a2e;margin-bottom:20px;
padding-bottom:15px;border-bottom:3px solid #00f260;display:flex;
align-items:center;gap:10px}}
.section-title::before{{content:'🔐';font-size:1.2em}}
.network-card{{background:linear-gradient(135deg,#667eea 0%,#764ba2 100%);
padding:30px;border-radius:15px;margin:20px 0;box-shadow:0 10px 30px rgba(0,0,0,0.2);
color:#fff}}
.network-name{{font-size:2em;font-weight:bold;margin-bottom:20px;
text-shadow:2px 2px 4px rgba(0,0,0,0.3);word-break:break-all}}
.detail{{background:rgba(255,255,255,0.2);padding:15px;border-radius:10px;
margin:10px 0;backdrop-filter:blur(10px)}}
.detail-label{{font-weight:600;opacity:0.9;margin-right:10px}}
.detail-value{{font-family:monospace;font-size:1.1em}}
.password-box{{background:linear-gradient(135deg,#00f260 0%,#0575e6 100%);
padding:35px;border-radius:15px;text-align:center;margin:30px 0;
box-shadow:0 15px 40px rgba(0,0,0,0.3);animation:pulse 2s infinite}}
@keyframes pulse{{0%,100%{{transform:scale(1)}}50%{{transform:scale(1.02)}}}}
.password-label{{font-size:1.2em;opacity:0.9;margin-bottom:15px;color:#fff}}
.password{{font-size:2.5em;font-weight:bold;font-family:monospace;
letter-spacing:3px;color:#fff;text-shadow:2px 2px 8px rgba(0,0,0,0.3);
word-break:break-all}}
.info-table{{width:100%;border-collapse:separate;border-spacing:0 10px}}
.info-table tr{{background:#fff;box-shadow:0 2px 8px rgba(0,0,0,0.1)}}
.info-table td{{padding:15px;border:none}}
.info-table td:first-child{{font-weight:600;color:#667eea;width:30%;
border-radius:10px 0 0 10px}}
.info-table td:last-child{{border-radius:0 10px 10px 0;font-family:monospace}}
.badge{{display:inline-block;padding:8px 16px;border-radius:20px;
font-size:0.85em;font-weight:600}}
.badge.success{{background:#d4edda;color:#155724}}
.badge.danger{{background:#f8d7da;color:#721c24}}
.badge.info{{background:#d1ecf1;color:#0c5460}}
.footer{{background:#1a1a2e;color:#fff;padding:20px;text-align:center;
font-size:0.9em}}
</style></head><body><div class="container">{content}<div class="footer">
Generated by PCAPCracker Pro • {timestamp}</div></div></body></html>"""

# DB
class DB:
    def __init__(self,p):
        self.p=p; self.init()
    def init(self):
        c=sqlite3.connect(self.p)
        c.execute("""CREATE TABLE IF NOT EXISTS res(id INTEGER PRIMARY KEY,
        ssid TEXT,bssid TEXT,pwd TEXT,pcap TEXT,ts TEXT,wl TEXT,status TEXT,
        hmz TEXT,wmz TEXT,method TEXT)""")
        try:
            c.execute("ALTER TABLE res ADD COLUMN method TEXT")
        except sqlite3.OperationalError:
            pass
        c.execute("""CREATE TABLE IF NOT EXISTS att(id INTEGER PRIMARY KEY,
        hmz TEXT,wmz TEXT,type TEXT,ts TEXT,cnt INT DEFAULT 1,
        UNIQUE(hmz,wmz,type))""")
        c.commit(); c.close()
    def save(self,ss,bs,pw,pc,wl,st,hm,wm,mt):
        c=sqlite3.connect(self.p)
        try:
            c.execute("""INSERT INTO res (ssid,bssid,pwd,pcap,ts,wl,status,hmz,wmz,method)
                        VALUES (?,?,?,?,?,?,?,?,?,?)""",
                     (ss,bs,pw,pc,datetime.now().isoformat(),wl,st,hm,wm,mt))
            c.commit()
        except sqlite3.Error as e:
            L.e(f"Erro ao salvar no banco de dados: {e}")
        finally:
            c.close()
    def reg(self,hm,wm,tp):
        c=sqlite3.connect(self.p)
        try:
            c.execute("""INSERT INTO att VALUES(NULL,?,?,?,?,1)
            ON CONFLICT(hmz,wmz,type) DO UPDATE SET cnt=cnt+1""",
            (hm,wm,tp,datetime.now().isoformat()))
            c.commit()
        except sqlite3.Error as e:
            L.e(f"Erro ao registrar tentativa: {e}")
        finally:
            c.close()
    def chk(self,hm,wm,tp,mx):
        c=sqlite3.connect(self.p)
        try:
            r=c.execute("SELECT cnt FROM att WHERE hmz=? AND wmz=? AND type=?",
                       (hm,wm,tp)).fetchone()
            return r and r[0]>=mx
        except sqlite3.Error as e:
            L.e(f"Erro ao verificar tentativa: {e}")
            return False
        finally:
            c.close()
    def all(self):
        c=sqlite3.connect(self.p)
        try:
            r=c.execute(
                "SELECT ssid,bssid,pwd,status,ts,method,wl FROM res ORDER BY ts DESC"
            ).fetchall()
            return r
        except sqlite3.Error as e:
            L.e(f"Erro ao recuperar resultados: {e}")
            return []
        finally:
            c.close()

    def wordlist_stats(self):
        c = sqlite3.connect(self.p)
        try:
            rows = c.execute(
                """SELECT wl, ssid, MAX(ts) as last_used
                   FROM res
                   WHERE status LIKE '%OK%' OR status LIKE '%CRACK%'
                   GROUP BY wl, ssid
                   ORDER BY wl"""
            ).fetchall()
        except sqlite3.Error as e:
            L.e(f"Erro ao recuperar wordlist stats: {e}")
            return []
        finally:
            c.close()

        stats = {}
        for wl, ssid, ts in rows:
            name = Path(wl).name if wl else "unknown"
            if name not in stats:
                stats[name] = {"name": name, "cracks": 0, "last_used": ts or "", "ssids": []}
            stats[name]["cracks"] += 1
            if ssid and ssid not in stats[name]["ssids"]:
                stats[name]["ssids"].append(ssid)
            if ts and ts > stats[name]["last_used"]:
                stats[name]["last_used"] = ts

        return sorted(stats.values(), key=lambda x: x["cracks"], reverse=True)

# Utils
def fhash(f):
    if not os.path.isfile(f): return None
    h=hashlib.md5()
    with open(f,'rb') as x: h.update(x.read())
    return h.hexdigest()
def run(cmd,cap=False):
    try:
        if cap: return subprocess.run(cmd,capture_output=True,text=True)
        return subprocess.run(cmd,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    except Exception as e:
        L.e(f"Erro ao executar comando {cmd}: {e}")
        return None
def valid(f): return os.path.isfile(f) and os.path.getsize(f)>0

# Sound alert
def play_sound():
    print("\a", end="", flush=True)
    try:
        import platform
        sys_name = platform.system()
        wav = _gen_wav()
        if sys_name == "Linux":
            for player in [["paplay"], ["aplay"], ["ffplay","-nodisp","-autoexit"]]:
                try:
                    subprocess.run(player + [wav], stdout=subprocess.DEVNULL,
                                   stderr=subprocess.DEVNULL, timeout=4)
                    break
                except FileNotFoundError:
                    continue
        elif sys_name == "Darwin":
            subprocess.run(["afplay", wav], stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, timeout=4)
        elif sys_name == "Windows":
            import winsound
            for freq in [600, 900, 1200]:
                winsound.Beep(freq, 200)
    except Exception:
        pass

def _gen_wav(path="/tmp/pcapcracker_alert.wav"):
    import struct, math, wave
    if os.path.exists(path):
        return path
    sr = 44100
    notes = [(784,0.12),(784,0.12),(784,0.12),(659,0.35),(0,0.05),(784,0.12),(659,0.35)]
    samples = []
    for freq, dur in notes:
        n = int(sr * dur)
        for i in range(n):
            if freq == 0:
                samples.append(0)
            else:
                env = min(i/max(int(sr*0.01),1), 1.0, (n-i)/max(int(sr*0.02),1))
                v = int(32767 * env * math.sin(2 * math.pi * freq * i / sr))
                samples.append(v)
    try:
        with wave.open(path, "w") as wf:
            wf.setnchannels(1)
            wf.setsampwidth(2)
            wf.setframerate(sr)
            wf.writeframes(struct.pack('<' + 'h' * len(samples), *samples))
    except Exception:
        pass
    return path

# ── Logger ────────────────────────────────────────────────
class L:
    G  = '\033[38;5;22m'
    LG = '\033[38;5;46m'
    RS = Style.RESET_ALL

    @staticmethod
    def _raw(s):
        return re.sub(r'\x1b\[[0-9;]*m', '', s)

    @staticmethod
    def box(title, lines):
        rw = max(len(L._raw(title)), max(len(L._raw(l)) for l in lines)) + 4
        bar = '─' * rw
        print(f"\n{L.G}┌{bar}┐{L.RS}")
        pad = rw - len(L._raw(title)) - 2
        print(f"{L.G}│{L.RS}{' '*(pad//2)}{title}{' '*(pad-pad//2)}{L.G}│{L.RS}")
        print(f"{L.G}├{bar}┤{L.RS}")
        for line in lines:
            rpad = rw - len(L._raw(line)) - 1
            print(f"{L.G}│{L.RS} {line}{' '*rpad}{L.G}│{L.RS}")
        print(f"{L.G}└{bar}┘{L.RS}\n")

    @staticmethod
    def success_box(ssid, bssid, pwd):
        play_sound()
        lines = [
            f"  {L.G}SSID     {L.RS}:: {L.LG}{ssid}{L.RS}",
            f"  {L.G}BSSID    {L.RS}:: \033[96m{bssid}\033[0m",
            f"  {L.G}PASSWORD {L.RS}:: {L.LG}{pwd}{L.RS}",
        ]
        L.box(f"{L.LG}ACCESS_GRANTED // PASSWORD CRACKED{L.RS}", lines)

    @staticmethod
    def i(m):  print(f"  {L.G}[*]{L.RS} {m}")
    @staticmethod
    def s(m):  print(f"  {L.LG}[+]{L.RS} {m}")
    @staticmethod
    def w(m):  print(f"  \033[33m[!]\033[0m {m}")
    @staticmethod
    def e(m):  print(f"  \033[31m[✗]\033[0m {m}")
    @staticmethod
    def p(m):  print(f"  {L.G}[~]{L.RS} {m}")
    @staticmethod
    def sect(title):
        bar = '─' * 52
        print(f"\n{L.G}{bar}{L.RS}")
        print(f"{L.G}  // {L.LG}{title.upper()}{L.RS}")
        print(f"{L.G}{bar}{L.RS}\n")


# ── AI Support ─────────────────────────────────────────────
class AI:
    def __init__(self):
        config = configparser.ConfigParser()
        try:
            config.read('config.ini')
            self.api_key = config.get('AI', 'GROQ_API_KEY', fallback=os.getenv("GROQ_API_KEY"))
            self.model = config.get('AI', 'MODEL', fallback='llama-3.3-70b-versatile')
        except Exception:
            self.api_key = os.getenv("GROQ_API_KEY")
            self.model = 'llama-3.3-70b-versatile'
        
        if not self.api_key:
            raise ValueError("GROQ_API_KEY não configurada no config.ini ou ambiente.")
            
        self.client = Groq(api_key=self.api_key)

    def analyze_ssid(self, ssid):
        prompt = f"""Analise o SSID de rede Wi-Fi '{ssid}' e sugira estratégias de ataque de dicionário.
        Identifique se o nome sugere um provedor específico (ex: VIVO, CLARO), modelo de roteador, 
        ou se parece ser um nome personalizado que pode conter padrões como datas, nomes próprios ou locais.
        Retorne uma análise curta e 3 sugestões de padrões de senha."""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Erro na análise de IA: {e}"

    def suggest_next_steps(self, results):
        if not results:
            return "Nenhum resultado para analisar."
        
        summary = "\n".join([f"SSID: {r[0]}, BSSID: {r[1]}, Status: {r[3]}" for r in results[:10]])
        prompt = f"""Com base nos seguintes resultados de tentativas de crack (algumas podem ter falhado):
        {summary}
        
        Sugira os próximos passos. Se muitas falharam, sugira tipos de wordlists ou regras do hashcat que poderiam ser mais eficazes."""
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[{"role": "user", "content": prompt}]
            )
            return response.choices[0].message.content
        except Exception as e:
            return f"Erro na sugestão de IA: {e}"

# ── HTML Generator ─────────────────────────────────────────
def _build_wordlist_section(wl_stats):
    if not wl_stats:
        return '<p class="empty">[ NO WORDLIST DATA YET ]</p>'

    max_cracks = max(s["cracks"] for s in wl_stats) or 1
    medals = ["🥇", "🥈", "🥉"]

    rows_html = ""
    for i, stat in enumerate(wl_stats):
        pct        = round(stat["cracks"] / max_cracks * 100)
        medal      = medals[i] if i < 3 else f"#{i+1}"
        ssid_tags  = " ".join(
            f'<span class="ssid-tag">{escape(s)}</span>'
            for s in stat["ssids"][:6]
        )
        more       = f'<span class="more-tag">+{len(stat["ssids"])-6} more</span>' \
                     if len(stat["ssids"]) > 6 else ""
        last       = stat["last_used"][:16].replace("T", " ") if stat["last_used"] else "—"
        rank_class = f"rank-{i}" if i < 3 else "rank-other"

        rows_html += f"""
<div class="wl-row {rank_class}" style="--delay:{i*0.08:.2f}s">
  <div class="wl-rank">{medal}</div>
  <div class="wl-info">
    <div class="wl-name">{escape(stat['name'])}</div>
    <div class="wl-ssids">{ssid_tags}{more}</div>
    <div class="wl-last">last hit :: {escape(last)}</div>
  </div>
  <div class="wl-bar-wrap">
    <div class="wl-bar" style="--pct:{pct}%"></div>
  </div>
  <div class="wl-count">{stat['cracks']:03d}<span class="wl-unit"> hits</span></div>
</div>"""

    return f"""
<div class="wl-section">
  <div class="section-hdr">wordlist leaderboard</div>
  <div class="wl-list">
    {rows_html}
  </div>
</div>"""


def gen_results_html(db):
    path = f"{cfg.HTML}/results.html"
    rows = db.all()
    wl_stats = db.wordlist_stats()

    seen = set(); unique = []
    for r in rows:
        key = (r[0], r[1], r[2])
        if key not in seen:
            seen.add(key); unique.append(r)
    total = len(unique)

    cards = ""
    for ssid, bssid, pwd, status, ts, method, wl in unique:
        wl_name = Path(wl).name if wl else "—"
        cards += f"""
<div class="card" data-aos="fade-up">
  <div class="card-header">
    <span class="led"></span>
    <span class="ssid-name">{escape(ssid)}</span>
    <span class="tag">{escape(method or 'hashcat').upper()}</span>
  </div>
  <div class="card-body">
    <div class="field"><span class="lbl">BSSID</span>
      <span class="val mono">{escape(bssid)}</span></div>
    <div class="field"><span class="lbl">ENCRYPTION</span>
      <span class="val mono">WPA/WPA2-PSK</span></div>
    <div class="field"><span class="lbl">WORDLIST</span>
      <span class="val mono wl-badge">{escape(wl_name)}</span></div>
    <div class="field"><span class="lbl">STATUS</span>
      <span class="val ok">{escape(status or 'CRACKED')}</span></div>
    <div class="field"><span class="lbl">TIMESTAMP</span>
      <span class="val mono">{escape(ts or '')}</span></div>
  </div>
  <div class="pwd-reveal">
    <div class="pwd-label">// ACCESS_GRANTED — PASSWORD CRACKED</div>
    <div class="pwd-value">{escape(pwd)}</div>
  </div>
</div>"""

    empty_msg = '<p class="empty">[ NO DATA — AWAITING ATTACK ]</p>' if not cards else ""
    wl_section = _build_wordlist_section(wl_stats)

    html = f"""<!DOCTYPE html>
<html lang="pt-BR"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>cyberwalisson :: results</title>
<style>
@import url('https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Orbitron:wght@700;900&display=swap');
*{{margin:0;padding:0;box-sizing:border-box}}
:root{{
  --green:#00ff41;--dkgreen:#00aa2a;--red:#ff003c;--cyan:#00f6ff;
  --gold:#ffd700;--silver:#c0c0c0;--bronze:#cd7f32;
  --bg:#0a0a0a;--panel:#0d0d0d;--border:#1a1a1a;--glow:rgba(0,255,65,.18);
}}
body{{background:var(--bg);color:var(--green);font-family:'Share Tech Mono',monospace;
  min-height:100vh;overflow-x:hidden}}
body::before{{content:'';position:fixed;inset:0;
  background:repeating-linear-gradient(0deg,transparent,transparent 2px,
  rgba(0,0,0,.15) 2px,rgba(0,0,0,.15) 4px);
  pointer-events:none;z-index:9999}}
#matrix{{position:fixed;top:0;left:0;width:100%;height:100%;z-index:0;opacity:.07;pointer-events:none}}
.wrapper{{position:relative;z-index:1;max-width:1100px;margin:0 auto;padding:30px 20px}}
.site-header{{text-align:center;padding:40px 0 30px;border-bottom:1px solid var(--border);margin-bottom:40px}}
.lock-span{{display:inline-block;font-size:3.5em;animation:lockBreak2 2.5s ease-in-out infinite}}
@keyframes lockBreak2{{
  0%,25%{{filter:drop-shadow(0 0 8px #00ff41)}}
  55%{{filter:drop-shadow(0 0 25px #ff003c);transform:scale(1.15) rotate(-8deg)}}
  65%{{filter:drop-shadow(0 0 35px #00f6ff);transform:scale(1.25) rotate(0deg)}}
  80%,100%{{filter:drop-shadow(0 0 12px #00f6ff);transform:scale(1)}}
}}
.lock-span.open{{animation:lockOpen 2.5s ease-in-out infinite}}
@keyframes lockOpen{{
  0%,55%{{opacity:0;transform:scale(.5)}}
  65%,100%{{opacity:1;transform:scale(1);filter:drop-shadow(0 0 18px #00f6ff)}}
}}
.site-title{{font-family:'Orbitron',sans-serif;font-size:clamp(1.8em,5vw,3.2em);
  font-weight:900;letter-spacing:.1em;
  background:linear-gradient(90deg,var(--green),var(--cyan),var(--green));
  background-size:200%;-webkit-background-clip:text;-webkit-text-fill-color:transparent;
  animation:shimmer 3s linear infinite}}
@keyframes shimmer{{0%{{background-position:0%}}100%{{background-position:200%}}}}
.site-sub{{color:var(--dkgreen);font-size:.9em;margin-top:8px;letter-spacing:.2em}}
.blink{{animation:blink .8s step-end infinite}}
@keyframes blink{{0%,100%{{opacity:1}}50%{{opacity:0}}}}
.stats-bar{{display:flex;gap:20px;flex-wrap:wrap;margin-bottom:40px}}
.stat{{flex:1;min-width:180px;background:var(--panel);border:1px solid #1e1e1e;
  border-left:3px solid var(--green);padding:18px;
  box-shadow:inset 0 0 20px rgba(0,255,65,.04)}}
.stat-lbl{{font-size:.75em;color:#555;letter-spacing:.15em;text-transform:uppercase}}
.stat-num{{font-size:2.4em;color:var(--green);font-family:'Orbitron',sans-serif;
  text-shadow:0 0 15px var(--green)}}
.section-hdr{{font-size:.8em;color:#333;letter-spacing:.3em;text-transform:uppercase;
  margin-bottom:25px;display:flex;align-items:center;gap:12px}}
.section-hdr::before{{content:'';flex:1;height:1px;background:linear-gradient(90deg,transparent,#1e1e1e)}}
.section-hdr::after{{content:'';flex:1;height:1px;background:linear-gradient(90deg,#1e1e1e,transparent)}}
.card{{background:var(--panel);border:1px solid #181818;margin-bottom:24px;
  box-shadow:0 0 0 1px #111,0 4px 30px rgba(0,0,0,.6);
  animation:fadeSlide .5s ease both}}
@keyframes fadeSlide{{from{{opacity:0;transform:translateY(20px)}}to{{opacity:1;transform:translateY(0)}}}}
.card-header{{display:flex;align-items:center;gap:12px;padding:12px 20px;
  background:#0f0f0f;border-bottom:1px solid #181818}}
.led{{width:10px;height:10px;border-radius:50%;background:var(--green);
  box-shadow:0 0 8px var(--green);animation:pulse .9s ease-in-out infinite alternate}}
@keyframes pulse{{from{{opacity:.4}}to{{opacity:1}}}}
.ssid-name{{flex:1;font-size:1.1em;color:#eee;letter-spacing:.05em;word-break:break-all}}
.tag{{font-size:.7em;padding:3px 10px;border:1px solid var(--dkgreen);
  color:var(--dkgreen);letter-spacing:.1em}}
.card-body{{padding:18px 20px;display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:10px}}
.field{{display:flex;flex-direction:column;gap:3px}}
.lbl{{font-size:.65em;color:#444;letter-spacing:.2em}}
.val{{font-size:.9em;color:#aaa}}
.mono{{font-family:'Share Tech Mono',monospace}}
.ok{{color:var(--green);text-shadow:0 0 8px var(--green)}}
.wl-badge{{color:var(--cyan);font-size:.82em;
  border:1px solid rgba(0,246,255,.25);padding:1px 6px;border-radius:3px}}
.pwd-reveal{{padding:20px;background:#080808;border-top:1px solid #1a1a1a;text-align:center}}
.pwd-label{{font-size:.7em;color:var(--dkgreen);letter-spacing:.25em;margin-bottom:10px}}
.pwd-value{{font-size:1.8em;color:var(--cyan);font-family:'Orbitron',sans-serif;
  letter-spacing:.12em;word-break:break-all;
  text-shadow:0 0 20px var(--cyan),0 0 40px rgba(0,246,255,.4)}}
.empty{{color:#333;text-align:center;padding:60px;letter-spacing:.2em}}
.wl-section{{margin:50px 0}}
.wl-list{{display:flex;flex-direction:column;gap:14px}}
.wl-row{{
  display:grid;
  grid-template-columns:48px 1fr 220px 80px;
  align-items:center;
  gap:16px;
  background:var(--panel);
  border:1px solid #181818;
  padding:16px 20px;
  position:relative;
  overflow:hidden;
  animation:fadeSlide .5s ease calc(var(--delay)) both;
  transition:border-color .3s,box-shadow .3s;
}}
.wl-row:hover{{
  border-color:rgba(0,255,65,.3);
  box-shadow:0 0 20px rgba(0,255,65,.06),inset 0 0 40px rgba(0,255,65,.02);
}}
.wl-row.rank-0{{border-left:3px solid var(--gold);}}
.wl-row.rank-0 .wl-bar{{background:linear-gradient(90deg,var(--gold),#ffe87c)!important;
  box-shadow:0 0 12px rgba(255,215,0,.5)!important}}
.wl-row.rank-0 .wl-count{{color:var(--gold);text-shadow:0 0 10px var(--gold)}}
.wl-row.rank-1{{border-left:3px solid var(--silver);}}
.wl-row.rank-1 .wl-bar{{background:linear-gradient(90deg,#a8a8a8,var(--silver))!important;
  box-shadow:0 0 10px rgba(192,192,192,.4)!important}}
.wl-row.rank-1 .wl-count{{color:var(--silver)}}
.wl-row.rank-2{{border-left:3px solid var(--bronze);}}
.wl-row.rank-2 .wl-bar{{background:linear-gradient(90deg,#a0522d,var(--bronze))!important;
  box-shadow:0 0 10px rgba(205,127,50,.4)!important}}
.wl-row.rank-2 .wl-count{{color:var(--bronze)}}
.wl-row.rank-other{{border-left:3px solid #1e1e1e;}}
.wl-rank{{font-size:1.6em;text-align:center;line-height:1}}
.wl-info{{min-width:0}}
.wl-name{{font-size:.95em;color:#ddd;letter-spacing:.04em;
  white-space:nowrap;overflow:hidden;text-overflow:ellipsis}}
.wl-ssids{{display:flex;flex-wrap:wrap;gap:5px;margin-top:7px}}
.ssid-tag{{font-size:.65em;padding:2px 8px;background:#111;
  border:1px solid #222;color:#888;border-radius:3px;
  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;max-width:160px}}
.more-tag{{font-size:.65em;padding:2px 8px;color:#444;border:1px solid #1a1a1a;border-radius:3px}}
.wl-last{{font-size:.65em;color:#333;margin-top:6px;letter-spacing:.1em}}
.wl-bar-wrap{{
  height:8px;background:#111;border-radius:4px;
  overflow:hidden;position:relative;
}}
.wl-bar{{
  height:100%;width:0;
  background:linear-gradient(90deg,var(--dkgreen),var(--green));
  box-shadow:0 0 10px rgba(0,255,65,.5);
  border-radius:4px;
  transition:width 1.2s cubic-bezier(.22,1,.36,1);
}}
.wl-count{{
  font-family:'Orbitron',sans-serif;
  font-size:1.3em;
  color:var(--green);
  text-shadow:0 0 12px var(--green);
  text-align:right;
  white-space:nowrap;
}}
.wl-unit{{font-size:.5em;color:#444;letter-spacing:.1em;font-family:'Share Tech Mono',monospace}}
.site-footer{{text-align:center;padding:30px;font-size:.7em;color:#222;
  border-top:1px solid #111;margin-top:40px;letter-spacing:.15em}}
</style>
</head>
<body>
<canvas id="matrix"></canvas>
<div class="wrapper">
  <header class="site-header">
    <div style="position:relative;display:inline-block;margin-bottom:12px">
      <span class="lock-span">🔒</span>
      <span class="lock-span open" style="position:absolute;left:0">🔓</span>
    </div>
    <div class="site-title">cyberwalisson</div>
    <div class="site-sub">[ WPA/WPA2 &nbsp;·&nbsp; CRACKED RESULTS &nbsp;·&nbsp; <span class="blink">■</span> LIVE ]</div>
  </header>
  <div class="stats-bar">
    <div class="stat">
      <div class="stat-lbl">// passwords cracked</div>
      <div class="stat-num">{total:03d}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">// wordlists active</div>
      <div class="stat-num">{len(wl_stats):03d}</div>
    </div>
    <div class="stat">
      <div class="stat-lbl">// last update</div>
      <div class="stat-num" style="font-size:1em;padding-top:8px">
        {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
      </div>
    </div>
  </div>
  {wl_section}
  <div class="section-hdr" style="margin-top:40px">target networks</div>
  {cards}{empty_msg}
  <footer class="site-footer">
    cyberwalisson :: pcapcracker pro &nbsp;|&nbsp; {datetime.now().strftime("%Y")} &nbsp;|&nbsp;
    <span style="color:var(--green)">[ AUTHORIZED PENTEST USE ONLY ]</span>
  </footer>
</div>
<script>
const c=document.getElementById('matrix'),ctx=c.getContext('2d');
function resize(){{c.width=window.innerWidth;c.height=window.innerHeight}}
resize();window.addEventListener('resize',resize);
const cols=Math.floor(c.width/16);const drops=Array(cols).fill(1);
const chars='アイウエオカキクケコ0123456789ABCDEF<>[]{{}}01';
function draw(){{
  ctx.fillStyle='rgba(0,0,0,0.05)';ctx.fillRect(0,0,c.width,c.height);
  ctx.fillStyle='#00ff41';ctx.font='14px monospace';
  drops.forEach((y,i)=>{{
    ctx.fillText(chars[Math.floor(Math.random()*chars.length)],i*16,y*16);
    if(y*16>c.height&&Math.random()>0.975)drops[i]=0;
    drops[i]++;
  }});
}}
setInterval(draw,50);
(function(){{
  const observer=new IntersectionObserver((entries)=>{{
    entries.forEach(e=>{{
      if(e.isIntersecting){{
        const bar=e.target.querySelector('.wl-bar');
        if(bar){{
          const pct=bar.style.getPropertyValue('--pct')||bar.getAttribute('data-pct');
          bar.style.width=bar.style.getPropertyValue('--pct')||'0%';
          const m=bar.getAttribute('style')||'';
          const match=m.match(/--pct:([^;]+)/);
          if(match) bar.style.width=match[1].trim();
        }}
        observer.unobserve(e.target);
      }}
    }});
  }},{{threshold:0.1}});
  document.querySelectorAll('.wl-row').forEach(r=>observer.observe(r));
  setTimeout(()=>{{
    document.querySelectorAll('.wl-bar').forEach(bar=>{{
      const m=(bar.getAttribute('style')||'').match(/--pct:([^;]+)/);
      if(m&&bar.style.width==='') bar.style.width=m[1].trim();
    }});
  }},300);
}})();
document.querySelectorAll('.pwd-value').forEach(el=>{{
  const full=el.textContent;el.textContent='';let i=0;
  const iv=setInterval(()=>{{
    el.textContent+=full[i++];
    if(i>=full.length)clearInterval(iv);
  }},60);
}});
</script>
</body></html>"""

    try:
        with open(path, 'w', encoding='utf-8') as f:
            f.write(html)
        L.s(f"results.html atualizado ({total} senha(s), {len(wl_stats)} wordlist(s)): {path}")
        return path
    except Exception as e:
        L.e(f"Erro ao salvar results.html: {e}")
        return None


def gen_html(data, tp="extract"):
    ts=datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    fname=f"extract_{data['ssid'][:20]}_{ts}.html"
    content=f"""<div class="header">
<h1>📦 HASH EXTRACTION</h1>
<div class="subtitle">Network Handshake Capture</div></div>
<div class="stats">
<div class="stat-card success"><div class="stat-label">Extracted</div>
<div class="stat-value">✓</div></div>
<div class="stat-card info"><div class="stat-label">Format</div>
<div class="stat-value" style="font-size:1.5em">22000</div></div></div>
<div class="content">
<div class="section"><h2 class="section-title">Network Info</h2>
<div class="network-card">
<div class="network-name">{escape(data['ssid'])}</div>
<div class="detail"><span class="detail-label">BSSID:</span>
<span class="detail-value">{escape(data['bssid'])}</span></div>
<div class="detail"><span class="detail-label">Method:</span>
<span class="detail-value">{data['method']}</span></div></div></div>
<div class="section"><h2 class="section-title">Files</h2>
<table class="info-table"><tr><td>PCAP Source</td><td>{escape(data['pcap'])}</td></tr>
<tr><td>Hash File</td><td>{escape(data['hash'])}</td></tr>
</table></div></div>"""

    path=f"{cfg.HTML}/{fname}"
    L.p(f"Gerando HTML: {path}")
    try:
        with open(path,'w',encoding='utf-8') as f:
            f.write(HTML_TPL.format(title=fname.replace('.html',''),content=content,
                    timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
        L.s(f"HTML salvo: {path}")
        return path
    except Exception as e:
        L.e(f"Erro ao salvar HTML {path}: {e}")
        return None


# ── JSON Logger ────────────────────────────────────────────
def log_json(db_or_data, tp="crack"):
    if tp == "crack":
        path = f"{cfg.JSON}/results.json"
        rows = db_or_data.all()
        wl_stats = db_or_data.wordlist_stats()

        seen = set(); unique = []
        for r in rows:
            key = (r[0], r[1], r[2])
            if key not in seen:
                seen.add(key)
                unique.append({
                    "ssid": r[0], "bssid": r[1], "password": r[2],
                    "status": r[3], "timestamp": r[4],
                    "method": r[5], "wordlist": r[6]
                })
        payload = {
            "generated": datetime.now().isoformat(),
            "total": len(unique),
            "wordlist_stats": wl_stats,
            "results": unique
        }
        L.p(f"Atualizando results.json ({len(unique)} senha(s))")
        try:
            with open(path, 'w', encoding='utf-8') as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
            L.s(f"results.json atualizado: {path}")
            return path
        except Exception as e:
            L.e(f"Erro ao salvar results.json: {e}")
            return None

    else:  # extract
        path = f"{cfg.JSON}/extractions.json"
        data = db_or_data
        try:
            existing = []
            if os.path.isfile(path):
                with open(path, 'r', encoding='utf-8') as f:
                    existing = json.load(f).get("extractions", [])
            key = (data.get("ssid",""), data.get("pcap",""))
            existing = [e for e in existing if (e.get("ssid",""), e.get("pcap","")) != key]
            existing.append(data)
            payload = {"generated": datetime.now().isoformat(),
                       "total": len(existing), "extractions": existing}
            with open(path, 'w', encoding='utf-8') as f:
                json.dump(payload, f, indent=2, ensure_ascii=False)
            L.s(f"extractions.json atualizado ({len(existing)} entrada(s)): {path}")
            return path
        except Exception as e:
            L.e(f"Erro ao salvar extractions.json: {e}")
            return None


# ── Extractor ──────────────────────────────────────────────
class Ext:
    MAC=re.compile(r"(?:[0-9A-Fa-f]{2}[:\-]){5}[0-9A-Fa-f]{2}")
    @staticmethod
    def extract(pcap,force=False):
        base=Path(pcap).stem; out=f"{cfg.HASH}/{base}.22000"
        if os.path.exists(out) and valid(out) and not force:
            L.i(f"Hash existe: {base}.22000"); return out
        L.p(f"Extraindo: {base}")
        pconv=pcap
        if pcap.lower().endswith('.scap'):
            tmp=f"{cfg.HASH}/{base}.pcapng"
            run(["tshark","-r",pcap,"-Y","eapol||wpa","-w",tmp])
            pconv=tmp
        run(["hcxpcapngtool","-o",out,pconv])
        if valid(out):
            ss,bs,mt=Ext.parse(out)
            L.s(f"Hash extraído: {base}.22000")
            print(f"  {Fore.CYAN}├─{Style.RESET_ALL} SSID: {Fore.CYAN}{ss}{Style.RESET_ALL}")
            print(f"  {Fore.CYAN}└─{Style.RESET_ALL} BSSID: {Fore.MAGENTA}{bs}{Style.RESET_ALL}")
            data={'ssid':ss,'bssid':bs,'method':mt,'pcap':base,'hash':f"{base}.22000",
                  'ts':datetime.now().isoformat()}
            hp=gen_html(data,'extract')
            log_json(data, 'extract')
            if hp: L.s(f"HTML de extração gerado: {Path(hp).name}")
            return out
        L.e(f"Falha: {base}")
        return None

    @staticmethod
    def _clean_ssid(s):
        if not s: return ""
        s = s.strip().strip('"\'').strip()
        s = re.sub(r'[\x00-\x1f\x7f]', '', s)
        if not (1 <= len(s) <= 32): return ""
        _junk = re.compile(
            r'(?i)(copyright|\(c\)\s*\d{4}|zeroBeat|hcxtools|hcxdump|hcxhashtool'
            r'|hashcat|version\s+\d|\d+\.\d+\.\d+|by\s+\w+\s+\w+|license'
            r'|www\.|http|\.com|\.org|wpa_supplicant|ieee\s*802)',
            re.IGNORECASE
        )
        if _junk.search(s): return ""
        if not re.search(r'[a-zA-Z0-9]', s): return ""
        return s

    @staticmethod
    def parse(hf):
        ss, bs, mt = "UNKNOWN", "UNKNOWN", "none"
        try:
            r0 = run(["hcxhashtool", "-i", hf, "--essid-to-stdout"], cap=True)
            if r0 and r0.stdout:
                for ln in r0.stdout.splitlines():
                    cand = Ext._clean_ssid(ln.strip())
                    if cand: ss = cand; mt = "hcx-essid"; break
        except Exception:
            pass
        if ss == "UNKNOWN" or bs == "UNKNOWN":
            try:
                r1 = run(["hcxhashtool", "-i", hf, "--info=stdout"], cap=True)
                if r1 and r1.returncode == 0:
                    txt = (r1.stdout or "") + (r1.stderr or "")
                    if ss == "UNKNOWN":
                        for pat in [r"(?i)^\s*ESSID\s*[:=]\s*(.+?)$",
                                    r"(?i)^\s*SSID\s*[:=]\s*(.+?)$",
                                    r"(?i)^\s*network\s+name\s*[:=]\s*(.+?)$"]:
                            m2 = re.search(pat, txt, re.MULTILINE)
                            if m2:
                                cand = Ext._clean_ssid(m2.group(1))
                                if cand: ss = cand; mt = "hcx-info"; break
                    if bs == "UNKNOWN":
                        for pat in [r"(?i)^\s*MAC_AP\s*[:=]\s*([0-9A-Fa-f:]{17})",
                                    r"(?i)^\s*BSSID\s*[:=]\s*([0-9A-Fa-f:]{17})",
                                    r"(?i)^\s*AP\s+MAC\s*[:=]\s*([0-9A-Fa-f:]{17})"]:
                            m2 = re.search(pat, txt, re.MULTILINE)
                            if m2: bs = m2.group(1).replace("-", ":").lower(); break
            except Exception:
                pass
        if ss == "UNKNOWN" or bs == "UNKNOWN":
            try:
                with open(hf, "r", errors="ignore") as fh:
                    for ln in fh:
                        ln = ln.strip()
                        if not ln or not ln.startswith("WPA"): continue
                        pts = ln.split("*")
                        if len(pts) < 6: continue
                        if bs == "UNKNOWN" and len(pts) > 3:
                            mac_raw = pts[3]
                            if len(mac_raw) == 12 and re.fullmatch(r'[0-9a-fA-F]{12}', mac_raw):
                                bs = ":".join(mac_raw[i:i+2] for i in range(0, 12, 2)).lower()
                                mt = "fmt"
                        if ss == "UNKNOWN" and len(pts) > 5 and pts[5]:
                            try:
                                dec = bytes.fromhex(pts[5]).decode("utf-8", errors="ignore").strip()
                                cand = Ext._clean_ssid(dec)
                                if cand: ss = cand; mt = "fmt"; continue
                            except Exception:
                                pass
                            cand = Ext._clean_ssid(pts[5])
                            if cand and re.match(r'^[\x20-\x7e]+$', cand):
                                ss = cand; mt = "fmt-ascii"
                        if ss != "UNKNOWN" and bs != "UNKNOWN": break
            except Exception:
                pass
        if ss == "UNKNOWN":
            try:
                r3 = run(["strings", "-n", "2", hf], cap=True)
                if r3 and r3.stdout:
                    for ln in r3.stdout.splitlines():
                        cand = Ext._clean_ssid(ln.strip())
                        if (cand and 2 <= len(cand) <= 32
                                and not re.fullmatch(r'[0-9a-fA-F]+', cand)
                                and not re.search(r'\s{2,}', cand)
                                and re.search(r'[a-zA-Z0-9]', cand)):
                            ss = cand; mt = "strings"; break
            except Exception:
                pass
        return ss, bs, mt


# ── Attacker ───────────────────────────────────────────────
class Att:
    def __init__(self,db): self.db=db
    def hc(self,hf,wl,rules=None):
        if not valid(hf) or not valid(wl): L.e("Arquivo inválido"); return None
        hm,wm=fhash(hf),fhash(wl)
        if self.db.chk(hm,wm,"hc",cfg.MAX_ATT): L.w("Já atacado"); return None
        cmd=["hashcat","-m","22000","-a","0",hf,wl,"--potfile-path",cfg.POT,
             "--opencl-device-types","1","--force","--quiet"]
        if rules: cmd+=["-r",rules]
        L.p(f"Hashcat: {Path(hf).name} + {Path(wl).name}")
        run(cmd); self.db.reg(hm,wm,"hc")
        pwd=self._chk(hf)
        if pwd:
            ss,bs,_=Ext.parse(hf)
            L.success_box(ss,bs,pwd)
            self.db.save(ss,bs,pwd,Path(hf).name,Path(wl).name,"OK-HC",hm,wm,"hashcat")
            gen_results_html(self.db)
            log_json(self.db, 'crack')
        else:
            L.w("Não encontrada")
        return pwd
    def _chk(self,hf):
        r=run(["hashcat","-m","22000","--show",hf,"--potfile-path",cfg.POT],cap=True)
        if r and r.stdout:
            for ln in r.stdout.splitlines():
                pts=ln.split(":")
                if len(pts)>=2: return pts[-1].strip()
        return None


# ── SSID Map ───────────────────────────────────────────────
def build_ssid_map():
    ssid_map = {}
    if not os.path.exists(cfg.HASH): return {}
    hfiles = [f for f in os.listdir(cfg.HASH)
              if f.endswith('.22000') and valid(f"{cfg.HASH}/{f}")]
    for hf in hfiles:
        path = f"{cfg.HASH}/{hf}"
        ss, bs, _ = Ext.parse(path)
        key = ss if ss != "UNKNOWN" else Path(hf).stem
        if key not in ssid_map:
            ssid_map[key] = []
        ssid_map[key].append(path)
    return ssid_map

def select_ssid(ssid_map):
    if not ssid_map:
        L.e("no hashes available — check pcap/ folder"); return None, None
    G = '\033[38;5;22m'; LG = '\033[38;5;46m'; RS = '\033[0m'
    ssids = list(ssid_map.keys())
    print(f"\n  {G}// available targets{RS}\n  {G}{'─'*46}{RS}")
    for i, s in enumerate(ssids):
        n = len(ssid_map[s])
        print(f"  {G}[{LG}{i:02d}{G}]{RS}  {LG}{s}{RS}  {G}// {n} hash{'es' if n>1 else ''}{RS}")
    print(f"  {G}{'─'*46}{RS}")
    try:
        idx = int(input(f"\n  {G}[{LG}>{G}]{RS} select target id: ").strip())
        ssid = ssids[idx]
        L.i(f"target locked :: {LG}{ssid}{RS}")
        return ssid, ssid_map[ssid]
    except (ValueError, IndexError):
        L.e("invalid selection"); return None, None

def select_wordlist():
    wls = [f for f in os.listdir(cfg.WL) if valid(f"{cfg.WL}/{f}")]
    if not wls:
        L.e("no wordlists found in wordlist/ folder"); return None
    G = '\033[38;5;22m'; LG = '\033[38;5;46m'; RS = '\033[0m'
    print(f"\n  {G}// available wordlists\n  {'─'*46}{RS}")
    for i, w in enumerate(wls):
        sz = os.path.getsize(f"{cfg.WL}/{w}")
        sz_lbl = f"{sz//1024}K" if sz < 1024*1024 else f"{sz//1024//1024}M"
        print(f"  {G}[{LG}{i:02d}{G}]{RS}  {w}  {G}// {sz_lbl}{RS}")
    print(f"  {G}{'─'*46}{RS}")
    try:
        idx = int(input(f"\n  {G}[{LG}>{G}]{RS} select wordlist id: ").strip())
        L.i(f"wordlist loaded :: {LG}{wls[idx]}{RS}")
        return f"{cfg.WL}/{wls[idx]}"
    except (ValueError, IndexError):
        L.e("invalid selection"); return None


# ── CLI ────────────────────────────────────────────────────
class CLI:
    def __init__(self):
        self.db=DB(cfg.DB); self.att=Att(self.db); self.ai=AI()
        self.ssid_map = {}

    def banner(self):
        G  = '\033[38;5;22m'; LG = '\033[38;5;46m'
        RS = Style.RESET_ALL;  Y  = Fore.YELLOW
        mask = f"""
{G}  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░{RS}
{G}  ░  {LG} ██████╗██╗   ██╗██████╗ ███████╗██████╗{G}           ░{RS}
{G}  ░  {LG}██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗{G}          ░{RS}
{G}  ░  {LG}██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝{G}          ░{RS}
{G}  ░  {LG}██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗{G}          ░{RS}
{G}  ░  {LG}╚██████╗   ██║   ██████╔╝███████╗██║  ██║{G}          ░{RS}
{G}  ░  {LG} ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝{G}          ░{RS}
{G}  ░                                                       ░{RS}
{G}  ░  {Y}     w a l i s s o n  //  WPA/WPA2  //  v2.1 AI  {G}░{RS}
{G}  ░  {LG}  We are Anonymous. We are Legion.               {G}░{RS}
{G}  ░  {LG}  We do not forgive. We do not forget.           {G}░{RS}
{G}  ░  {LG}  Expect us.                                     {G}░{RS}
{G}  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░{RS}"""
        print(mask)

    def menu(self):
        n   = len(self.ssid_map)
        G   = '\033[38;5;22m'; LG  = '\033[38;5;46m'
        RS  = Style.RESET_ALL;  Y   = Fore.YELLOW
        bar = f"{G}  {'─'*50}{RS}"
        print(f"\n{bar}")
        print(f"{G}  // {LG}OPERATION MENU{RS}")
        print(f"{bar}")
        print(f"  {G}[{LG}1{G}]{RS}  target SSID  +  single wordlist")
        print(f"  {G}[{LG}2{G}]{RS}  target SSID  +  all wordlists")
        print(f"  {G}[{LG}3{G}]{RS}  ALL targets  +  all wordlists   {G}// FULL AUTO{RS}")
        print(f"  {G}[{LG}4{G}]{RS}  show cracked passwords")
        print(f"  {G}[{LG}5{G}]{RS}  export CSV")
        print(f"  {G}[{LG}6{G}]{RS}  {Y}AI Analysis (SSID Strategy){RS}")
        print(f"  {G}[{LG}7{G}]{RS}  {Y}AI Next Steps Suggestions{RS}")
        print(f"  {G}[{LG}0{G}]{RS}  disconnect")
        print(f"{bar}")
        print(f"  {G}targets_in_memory {LG}::{RS} {Y}{n}{RS}   "
              f"{G}session {LG}::{RS} {Y}{datetime.now().strftime('%H:%M:%S')}{RS}")
        print(f"{bar}\n")

    def auto_extract(self):
        G  = '\033[38;5;22m'; LG = '\033[38;5;46m'; RS = Style.RESET_ALL
        bar = f"{G}  {'─'*50}{RS}"
        print(f"\n{bar}")
        print(f"{G}  // {LG}SCANNING PCAP DIRECTORY{RS}")
        print(f"{bar}")
        if not os.path.exists(cfg.PCAP): os.makedirs(cfg.PCAP)
        pcaps = [f for f in os.listdir(cfg.PCAP)
                 if f.lower().endswith(('.pcap', '.pcapng', '.cap', '.scap'))]
        if not pcaps:
            L.w("no pcap files found in pcap/")
        else:
            L.i(f"{len(pcaps)} file(s) detected — starting hash extraction")
            for p in tqdm(pcaps, desc="  extracting", unit="pcap",
                          bar_format="  {l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}]"):
                Ext.extract(f"{cfg.PCAP}/{p}")
        self.ssid_map = build_ssid_map()
        if self.ssid_map:
            print(f"\n{bar}")
            print(f"{G}  // {LG}TARGETS IDENTIFIED{RS}")
            print(f"{bar}")
            for ssid, paths in self.ssid_map.items():
                n = len(paths)
                print(f"  {G}[+]{RS} {LG}{ssid}{RS}  {G}// {n} hash{'es' if n>1 else ''}{RS}")
            print(f"{bar}")
        else:
            L.w("no hashes available after extraction")
        print()

    def attack_ssid_wl(self):
        print(f"\n{Fore.CYAN}{'='*50}")
        print(f"{'ATAQUE: SSID + WORDLIST'.center(50)}")
        print(f"{'='*50}{Style.RESET_ALL}\n")
        ssid, hashes = select_ssid(self.ssid_map)
        if not ssid: return
        wl = select_wordlist()
        if not wl: return
        L.i(f"Alvo: {Fore.CYAN}{ssid}{Style.RESET_ALL} | WL: {Fore.YELLOW}{Path(wl).name}{Style.RESET_ALL}")
        cracked = False
        for hf in hashes:
            if self.att.hc(hf, wl): cracked = True
        if cracked: self.show()

    def attack_ssid_all_wl(self):
        print(f"\n{Fore.CYAN}{'='*50}")
        print(f"{'ATAQUE: SSID + TODAS WORDLISTS'.center(50)}")
        print(f"{'='*50}{Style.RESET_ALL}\n")
        ssid, hashes = select_ssid(self.ssid_map)
        if not ssid: return
        wls = [f"{cfg.WL}/{f}" for f in os.listdir(cfg.WL) if valid(f"{cfg.WL}/{f}")]
        if not wls: L.e("Sem wordlists na pasta wordlist/"); return
        L.i(f"Alvo: {Fore.CYAN}{ssid}{Style.RESET_ALL} | "
            f"{Fore.YELLOW}{len(wls)} wordlist(s){Style.RESET_ALL}")
        cracked = False
        for hf in hashes:
            for wl in tqdm(wls, desc=f"WL → {Path(hf).name}", unit="w"):
                if self.att.hc(hf, wl): cracked = True
        if cracked: self.show()
        L.s("operation complete")

    def attack_all_ssid_all_wl(self):
        print(f"\n{Fore.CYAN}{'='*50}")
        print(f"{'ATAQUE: TODOS SSIDs + TODAS WORDLISTS'.center(50)}")
        print(f"{'='*50}{Style.RESET_ALL}\n")
        if not self.ssid_map:
            L.e("Nenhum hash disponível. Verifique a pasta pcap/."); return
        wls = [f"{cfg.WL}/{f}" for f in os.listdir(cfg.WL) if valid(f"{cfg.WL}/{f}")]
        if not wls: L.e("Sem wordlists na pasta wordlist/"); return
        total_ssids = len(self.ssid_map)
        L.i(f"SSIDs: {Fore.CYAN}{total_ssids}{Style.RESET_ALL} | "
            f"Wordlists: {Fore.YELLOW}{len(wls)}{Style.RESET_ALL}")
        cracked = False
        for idx, (ssid, hashes) in enumerate(self.ssid_map.items(), 1):
            print(f"\n{Fore.CYAN}[{idx}/{total_ssids}]{Style.RESET_ALL} "
                  f"Alvo: {Fore.CYAN}{ssid}{Style.RESET_ALL}")
            for hf in hashes:
                for wl in tqdm(wls, desc=f"  WL → {Path(hf).name}", unit="w"):
                    if self.att.hc(hf, wl): cracked = True
        if cracked: self.show()
        L.s("operation complete")

    def show(self):
        print(f"\n{Fore.CYAN}{'='*50}")
        print(f"{'SENHAS QUEBRADAS'.center(50)}")
        print(f"{'='*50}{Style.RESET_ALL}\n")
        rs = self.db.all()
        if not rs: L.w("Nenhuma senha encontrada"); return
        print(f"{Fore.GREEN}Total: {len(rs)} senha(s){Style.RESET_ALL}\n")
        for r in rs:
            ss, bs, pw = r[0], r[1], r[2]
            lines = [
                f"{Fore.WHITE}SSID:{Style.RESET_ALL}   {Fore.CYAN}{ss[:40]}{Style.RESET_ALL}",
                f"{Fore.WHITE}BSSID:{Style.RESET_ALL}  {Fore.MAGENTA}{bs}{Style.RESET_ALL}",
                f"{Fore.WHITE}SENHA:{Style.RESET_ALL}  {Fore.GREEN}{pw}{Style.RESET_ALL}"
            ]
            L.box(f"{Fore.GREEN}✓ SENHA QUEBRADA{Style.RESET_ALL}", lines)

    def csv(self):
        rs=self.db.all()
        if not rs: L.w("Sem dados"); return
        out="export.csv"
        try:
            with open(out,"w") as f:
                f.write("ssid,bssid,password,status,timestamp,method,wordlist\n")
                for r in rs: f.write(",".join(str(x or "") for x in r)+"\n")
            L.s(f"CSV gerado: {out}")
        except Exception as e:
            L.e(f"Erro ao salvar CSV {out}: {e}")

    def ai_ssid_analysis(self):
        ssid, _ = select_ssid(self.ssid_map)
        if not ssid: return
        L.p(f"Analisando SSID '{ssid}' com IA...")
        analysis = self.ai.analyze_ssid(ssid)
        L.box("AI STRATEGY ANALYSIS", analysis.split('\n'))

    def ai_suggestions(self):
        L.p("Consultando IA para sugestões baseadas nos resultados atuais...")
        rs = self.db.all()
        suggestions = self.ai.suggest_next_steps(rs)
        L.box("AI NEXT STEPS", suggestions.split('\n'))

    def run(self):
        self.banner()
        self.auto_extract()
        while True:
            self.menu()
            op=input(f"\n{Fore.YELLOW}► Opção: {Style.RESET_ALL}").strip()
            if op=="1":   self.attack_ssid_wl()
            elif op=="2": self.attack_ssid_all_wl()
            elif op=="3": self.attack_all_ssid_all_wl()
            elif op=="4": self.show()
            elif op=="5": self.csv()
            elif op=="6": self.ai_ssid_analysis()
            elif op=="7": self.ai_suggestions()
            elif op=="0": print(f"{Fore.GREEN}Até logo!{Style.RESET_ALL}"); break
            else: L.e("Opção inválida")

if __name__=="__main__":
    cli=CLI()
    cli.run()
